version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:12.18.3
    working_directory: ~/app

jobs:
  deploy_test_environment:
    docker:
      - image: circleci/node:12.18.3
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: publish gh pages to one of the test environments
          command: ./tools/deploy-gh-pages-pr.sh
  test:
    executor: node-executor
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn danger ci --failOnErrors --id @brainhubeu/react-carousel
      - run: yarn lint
      - run: yarn test:unit:coverage
      - run:
          name: Generate coveralls config
          command: "echo repo_token: $COVERALLS_REPO_TOKEN > ./react-carousel/.coveralls.yml"
      - run: yarn build
      - persist_to_workspace:
          root: ~/app
          paths:
            - .git
            - node_modules
            - react-carousel/node_modules
            - react-carousel/lib
            - docs-www/node_modules
            - react-carousel/.coveralls.yml
            - react-carousel/coverage
  test-e2e:
    docker:
      - image: circleci/node:12.18.3
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Running E2E tests
          command: docker-compose -f ./docker-compose.e2e.yml up --build --exit-code-from e2e-test

  publish_package:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/app
      - run: git checkout .
      - run:
          name: Upload coverage to coveralls
          command: |
            cd react-carousel
            cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
      - run:
          name: configure GitHub user
          command: |
            git config --global user.email "robert@brainhub.pl"
            git config --global user.name "DevOps Brainhub"
            git remote -v
            git remote remove origin
            git remote add origin https://$GIT_TOKEN@github.com/brainhubeu/react-carousel
            git remote -v
      - run: git pull --no-edit origin $CIRCLE_BRANCH
      - run: git push origin $CIRCLE_BRANCH
      - run:
          name: npm publish
          command: npx semantic-release
      - run: sleep 10
      - run: git pull --no-edit origin $CIRCLE_BRANCH
      - run: git push origin $CIRCLE_BRANCH
      - run:
          name: publish gh pages
          command: ./tools/deploy-gh-pages.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - test-e2e
      - deploy_test_environment:
          filters:
            branches:
              ignore:
                - master
                - rc
      - publish_package:
          requires:
            - test
            - test-e2e
            - deploy_test_environment
          filters:
            branches:
              only:
                - master
