version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: yarn test-unit
      - run: yarn build
      - run: node -e "console.log(require('./lib/react-carousel'))"
      - run:
          name: publish gh pages for a given PR
          command: ./tools/deploy-gh-pages-pr.sh

  publish_package:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run:
          name: npm publish CDN version
          command: |
            sed -i 's/export default Carousel;/global.BrainhubeuReactCarousel = Carousel; export default Carousel;/g' src/components/Carousel.js
            sed -i 's/export default CarouselDots;/global.BrainhubeuReactCarouselDots = CarouselDots; export default CarouselDots;/g' src/components/CarouselDots.js
            sed -i 's/export default CarouselItem;/global.BrainhubeuReactCarouselItem = CarouselItem; export default CarouselItem;/g' src/components/CarouselItem.js
            sed -i 's/export default CarouselWrapper;/global.BrainhubeuReactCarouselWrapper = CarouselWrapper; export default CarouselWrapper;/g' src/components/CarouselWrapper.js
            yarn build
            sed -i 's/  "version": "\(.*\)",/  "version": "\1-cdn",/g' package.json
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish
            git config --global user.email "devops@brainhub.pl"
            git config --global user.name "DevOps Brainhub"
            git add .
            git stash
      - run:
          name: npm publish
          command: |
            yarn build
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish
      - run:
          name: publish gh pages
          command: ./tools/deploy-gh-pages.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - publish_package:
          requires:
            - test
          filters:
            branches:
              only:
                - master
